### ISSUE TITLE
Typo in RecordCnameObject struct

### ISSUE THREAD

**Issue by richardlock** [fanatic/go-infoblox#19]
Hi,

Thank you for the great library.  While using the library to update the terraform-provider-infoblox plugin, I noticed that one of the RecordCnameObject attributes is spelled incorrectly.  I think "Canoncial" should be "Canonical".

https://github.com/fanatic/go-infoblox/blob/d2a0c53da1cf587c82eac7e1d7ae3c35434c1301/record_cname.go#L15

Thanks, Richard

**Comment by richardlock** [comment]
Added PR.

**Comment by fanatic** [comment]
Thanks!!!

**Comment by richardlock** [comment]
Thanks Jason.
