### ISSUE TITLE
Closing connections

### ISSUE THREAD

**Issue by SJChacko** [fanatic/go-infoblox#30]
We've been having some timeout issues and they were partially fixed by adding defer resp.Body.Close() to resource.go, close header to request and a timeout to client. 

It seems usual in go to get an http response, process and immediately close the response body, the go-infoblox code passes the response on and it could be that it is not eventually closed in all cases. 

Issue discussed here https://stackoverflow.com/questions/33238518/what-could-happen-if-i-dont-close-response-body-in-golang

**Comment by fanatic** [comment]
I did a once-over of the response code and noticed a few bugs and hidden errors.  I also added response body closing in non-gzip responses.
